[[redirects]]
  from = "https://deploy-preview-38--epic-goldberg-1d6f10.netlify.app/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","SD","SY","ZW","US","ES"]}
  headers = {Link="<https://yam.finance>"}